# Generated by Django 4.1.3 on 2022-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('repassword', models.CharField(max_length=100)),
            ],
        ),
    ]
