# Generated by Django 4.1.3 on 2022-11-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register1',
            new_name='register',
        ),
    ]
