# Generated by Django 4.1.3 on 2022-11-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_register1_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
