# Generated by Django 4.1.3 on 2022-11-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_firstname_register_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Last_Name',
            new_name='last_name',
        ),
    ]
