# Generated by Django 4.1.3 on 2022-11-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_first_name_register_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registermodel',
        ),
    ]
