# Generated by Django 4.1.3 on 2022-11-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_register_registermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='dob',
        ),
    ]
