# Generated by Django 4.1.3 on 2022-11-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_registermodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='repassword',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
