# Generated by Django 4.1.3 on 2022-11-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_registermodel_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
