# Generated by Django 4.1.3 on 2022-11-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_registeruser_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registeruser',
            new_name='registermodel',
        ),
    ]
