# Generated by Django 4.1.3 on 2023-02-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='package',
        ),
    ]
