# Generated by Django 4.1.3 on 2023-02-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='img',
        ),
    ]
