# Generated by Django 4.1.3 on 2023-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_package_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('first_n', models.CharField(max_length=50)),
                ('last_n', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
