# Generated by Django 4.1.3 on 2023-02-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_relative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='id',
        ),
        migrations.AlterField(
            model_name='relative',
            name='p_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
