# Generated by Django 4.1.3 on 2023-02-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_relative_id_alter_relative_p_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relative',
        ),
    ]
