# Generated by Django 4.1.3 on 2023-02-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='docfullname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_n', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('loc', models.CharField(max_length=200)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_phone', models.IntegerField()),
                ('d_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('d_name', models.ManyToManyField(to='home.docfullname')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
