# Generated by Django 4.1.3 on 2023-02-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_patientlist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='d_name',
        ),
        migrations.DeleteModel(
            name='docfullname',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
