# Generated by Django 4.1.3 on 2023-02-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_username_patientlist_userchanav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlist',
            old_name='userchanav',
            new_name='username',
        ),
    ]
