# Generated by Django 4.1.3 on 2023-02-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_userchanav_patientlist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlist',
            old_name='username',
            new_name='username_id',
        ),
    ]
