# Generated by Django 4.1.3 on 2023-02-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_username_patientlist_username_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientList',
        ),
    ]
