# Generated by Django 4.1.3 on 2023-02-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_patientlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlist',
            old_name='username_id',
            new_name='username',
        ),
    ]
