# Generated by Django 4.1.3 on 2023-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_patientlist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='p_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='p_gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
