# Generated by Django 4.1.3 on 2023-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_patientlist_p_age_alter_patientlist_p_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlist',
            name='p_gender',
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='p_age',
            field=models.IntegerField(),
        ),
    ]
