# Generated by Django 4.1.3 on 2023-02-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_patientlist_p_gender_alter_patientlist_p_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='p_age',
            field=models.IntegerField(null=True),
        ),
    ]
