# Generated by Django 4.1.3 on 2023-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_patientlist_p_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlist',
            name='p_gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
