# Generated by Django 4.1.3 on 2023-02-24 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0048_remove_patientlist_id_alter_patientlist_p_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
