# Generated by Django 4.1.3 on 2023-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_patient_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_list',
            name='p_gender',
        ),
        migrations.AlterField(
            model_name='patient_list',
            name='p_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient_list',
            name='p_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PatientList',
        ),
    ]
