# Generated by Django 4.1.3 on 2023-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_remove_patient_list_p_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_list',
            name='p_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_list',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
    ]
