# Generated by Django 4.1.3 on 2023-02-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_patient_list_p_age_alter_patient_list_p_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=500)),
                ('improvement', models.CharField(max_length=500)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
    ]
