# Generated by Django 4.1.3 on 2023-02-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
