# Generated by Django 4.1.3 on 2023-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_myselectedoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='myselectedoption',
            name='selected_options',
            field=models.ManyToManyField(to='home.patient_list'),
        ),
        migrations.AlterField(
            model_name='myselectedoption',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
