# Generated by Django 4.1.3 on 2023-02-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_myselectedoption_selected_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySelectedOption',
        ),
    ]
