# Generated by Django 4.1.3 on 2023-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_myselectedoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.ManyToManyField(to='home.patient_list')),
            ],
        ),
        migrations.DeleteModel(
            name='MySelectedOption',
        ),
    ]
