# Generated by Django 4.1.3 on 2023-02-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_selection_delete_myselectedoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
