# Generated by Django 4.1.3 on 2023-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('loc', models.CharField(max_length=200)),
                ('d_email', models.EmailField(max_length=254, null=True)),
                ('d_phone', models.IntegerField(null=True)),
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=100)),
            ],
        ),
    ]
