# Generated by Django 4.1.3 on 2023-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='doctors',
            field=models.ManyToManyField(default='', to='home.doctor'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='options',
            field=models.ManyToManyField(default='', to='home.patient_list'),
        ),
    ]
