# Generated by Django 4.1.3 on 2023-02-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_userselection_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselection',
            name='radio_selection',
            field=models.CharField(default='', max_length=255),
        ),
    ]
