# Generated by Django 4.1.3 on 2023-02-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_userselection_radio_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselection',
            old_name='date',
            new_name='sch_date',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='radio_selection',
            new_name='sch_time',
        ),
    ]
