# Generated by Django 4.1.3 on 2023-02-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_rename_date_userselection_sch_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='options',
            new_name='listof_patient',
        ),
    ]
