# Generated by Django 4.1.3 on 2023-02-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_selection_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selection',
            new_name='Orders',
        ),
    ]
