# Generated by Django 4.1.3 on 2023-02-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_rename_selection_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
