# Generated by Django 4.1.3 on 2023-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('sch_date', models.DateField()),
                ('sch_time', models.CharField(max_length=255)),
                ('doctors', models.ManyToManyField(to='home.doctor')),
                ('listof_patient', models.ManyToManyField(to='home.patient_list')),
            ],
        ),
    ]
