# Generated by Django 4.1.3 on 2023-02-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
