# Generated by Django 4.1.3 on 2023-02-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0077_orders_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.ForeignKey(db_column='username', default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
