# Generated by Django 4.1.3 on 2023-03-01 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0078_orders_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('sch_date', models.DateField()),
                ('sch_time', models.CharField(max_length=255)),
                ('username', models.ForeignKey(db_column='username', default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
