# Generated by Django 4.1.3 on 2023-03-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_appointment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='listof_patient',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
