# Generated by Django 4.1.3 on 2023-03-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
