# Generated by Django 4.1.3 on 2023-03-07 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0085_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Booking',
        ),
    ]
