# Generated by Django 4.1.3 on 2023-03-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_rename_orders_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
