# Generated by Django 4.1.3 on 2023-03-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0087_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], max_length=7)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
                ('b_id', models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
