# Generated by Django 4.1.3 on 2023-03-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_remove_payment_b_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_and_time',
            new_name='p_date',
        ),
    ]
