# Generated by Django 4.1.3 on 2023-03-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_rename_date_and_time_payment_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Online', 'Online Payment'), ('Offline', 'Offline Payment')], max_length=7),
        ),
    ]
